server/accounts/urls.py
from . import views
from . import views as core_views
from django.conf.urls import url, include
from django.contrib.auth import views as auth_views
from django.urls import path

app_name = 'accounts'

urlpatterns = [
    url(r'^$', core_views.home, name='home'),
    url(r'products/$', core_views.product, name='product'),
    url(r'learn/$', core_views.learn, name='learn'),
    url(r'about/$', core_views.about, name='about'),
    # url(r'contact/$', core_views.contact, name='contact'),
    #url(r'testing/(?P<pid>[^/]+)$', core_views.testing, name='testing'),
    url(r'pricing/$', core_views.pricing, name='pricing'),
    url(r'^login/', views.login, name='login'),
    #url(r'^$', auth_views.logout, {'next_page': 'home'}, name='logout'),
    url(r'logout/$', views.logout_view, name='logout'),
    url(r'^signup/$', core_views.signup, name='signup'),
    url(r'^signup-confirm/$', core_views.signupConfirm, name='signupConfirm'),
    url(r'^account_activation_sent/$', core_views.account_activation_sent, name='account_activation_sent'),
    url(r'activate/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
        core_views.activate, name='activate'),
    url(r'^error/$', core_views.error, name='error'),
    url(r'downloadtool/$', views.downloadtool, name='downloadtool'),
    url(r'json/(?P<value>\d{3}).json', views.postal_json, name='postal_json_data'),


    url(r'account_activation/$', core_views.account_activation, name='account_activation'),
    # ---------------Password Reset------------------------------

    url(r'^password_reset/$', auth_views.password_reset,
        {'email_template_name': 'registration/password_reset_email.html',
         'subject_template_name': 'registration/password_reset_subject.txt',
         'post_reset_redirect': 'accounts:password_reset_done',
         'from_email': 'no-reply@sms-datatech.co.jp',
         }, name='password_reset'),

    url(r'^reset/done/$', auth_views.password_reset_complete, name='password_reset_complete'),

    url(r'^password_reset/done/$', auth_views.password_reset_done,
        {'template_name': 'registration/password_reset_done.html'}, name='password_reset_done'),

    url(r'^reset/(?P<uidb64>[^/]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
        auth_views.password_reset_confirm,
        {'post_reset_redirect': 'accounts:password_reset_complete'}, name='password_reset_confirm'),

    #     global
    url(r'global-home/$', core_views.global_home, name='global_home'),
    url(r'global-login/$', core_views.global_login, name='global_login'),
    url(r'global-contact/$', core_views.global_contact, name='global_contact'),
    url(r'global-signup/$', core_views.global_signup, name='global_signup'),

    #Social signup set password URL
    #url(r'set_password/$', core_views.social_signup_set_password, name='social_signup_set_password'),    

]

server/dashboard/urls.py
from . import views
from django.conf.urls import url, include
from django.contrib.auth import views as auth_views
from django.urls.conf import path
from django.conf.urls.i18n import i18n_patterns


app_name = 'dashboard'

urlpatterns = [
    path(r'home/', views.index, name = 'index'),
    path(r'upgrade/', views.upgrade, name='upgrade'),
    path(r'notification_settings/', views.notification_setting, name='notification_setting'),
    path(r'delete_account/', views.delete_account, name='delete_account'),
    url(r'^change_password/$', views.change_password, name='change_password'),
    url(r'^project/list/$', views.project_list, name='project_list'),
    url(r'^project/list/i18n/', include('django.conf.urls.i18n')),
    #path(r'project/schedule/', views.project_schedule, name = 'project_schedule'),
    path(r'settings/', views.settings, name='settings'),
    path(r'notification/change/', views.notification_change, name='notification_change'),
    url(r'account_setting_basic/$', views.account_setting_basic, name='account_setting_basic'),
    url(r'profile_change/$', views.profile_change, name='profile_change'),
    url(r'profile_change_finish/$', views.profile_change_finish, name='profile_change_finish'),
    url(r'password_change/$', views.PasswordChange.as_view(), name='password_change'),
    url(r'password_change_finish/$', views.password_change_finish, name='password_change_finish'),
    url(r'agreement_payment/$', views.agreement_payment, name='agreement_payment'),
    url(r'payment_change_bank/$', views.payment_change_bank, name='payment_change_bank'),
    url(r'payment_change_credit/$', views.payment_change_credit, name='payment_change_credit'),
    url(r'payment_change_finish/$', views.payment_change_finish, name='payment_change_finish'),
    url(r'plan_change/$', views.plan_change, name='plan_change'),
    url(r'plan_change_confirm/$', views.plan_change_confirm, name='plan_change_confirm'),
    url(r'plan_change_finish/$', views.plan_change_finish, name='plan_change_finish'),
    url(r'product_download/$', views.product_download, name='product_download'),
    url(r'system_error/$', views.system_error, name='system_error'),
    url(r'cancel/$', views.cancel, name='cancel'),
    url(r'cancel_finish/$', views.cancel_finish, name='cancel_finish'),
    path(r'ajax/$', views.managefiletype, name='managefiletype'),
    path(r'ajax1/$', views.edit_project, name='edit_project'),
    path(r'ajax2/$', views.edit_keyword, name='edit_keyword'),
    path(r'update/profile/', views.update_profile, name='update_profile'),
    path(r'project/data_order/', views.data_order, name='data_order'),
    path(r'project/data_order_form/', views.data_order_form, name='data_order_form'),
    path(r'project/data_order_confirm/', views.data_order_confirm, name='data_order_confirm'),
    path(r'project/data_order_done/', views.data_order_done, name='data_order_done'),

    #path(r'ScheduleForm/', views.schedule_form, name = 'schedule_form'),
    url(r'run/(?P<pid>[^/]+)$', views.run, name='run'),
    path(r'zip_data/(?P<pid>[^/]+)$', views.zip_data, name='zip_data'),
    path(r'delete/(?P<str:cname>[^/]+)$', views.delete_category, name='delete_category'),
    path(r'delete/(?p<pid>[^/]+)$', views.delete_project, name='delete_project'),
    path(r'delete_execution/(?P<pid>[^/]+)/(?P<eid>[^/]+)$', views.delete_execution, name='delete_execution'),
    url(r'product/$', views.product_type, name='product_type'),
    url(r'project/details/(?P<pid>[^/]+)$', views.project_details, name='project_details'),
    url(r'get_project/', views.get_project, name='get_project'),
    url(r'auto_refresh/', views.auto_refresh, name='auto_refresh'),

    url(r'email_change/$', views.email_change, name='email_change'),

    #---------Payment-------------------------------------------
    url(r'^cart$', views.ShowCartView.as_view(), name='cart'),
    #url(r'^create-payment$', views.CreatePaymentView.as_view(), name='create-payment'),
    #url(r'^execute-payment$', views.ExecutePaymentView.as_view(), name='execute-payment'),
    url(r'upgrade/payment', views.ExecutePaymentView, name='ExecutePaymentView'),
]

server/saas/urls.py
from . import views as core_views
from django.conf.urls import url

app_name = 'saas'

urlpatterns = [
    url(r'^saas/start/', core_views.start, name='start'),
    url(r'^saas/getLogin', core_views.get_login, name='get_login'),
    url(r'^saas/content', core_views.url_content_sel, name='url_content_sel'),
    url(r'^saas/procedure', core_views.get_procedure, name='get_procedure'),
    url(r'^saas/', core_views.process, name='process'),
    url(r'^pigdata-saas/', core_views.pigdata, name='pigdata'),
]

server/web_rpa/urls.py
from django.contrib import admin
from django.urls import path
from django.urls.conf import include
from django.conf.urls import url
from django.views.generic.base import RedirectView
from django.conf.urls.i18n import i18n_patterns

urlpatterns = [
    #path('', RedirectView.as_view(url='dashboard')),
    path('', include('accounts.urls')),
    path('api/v1/core/', include('api_v1.core.urls')),
    path('api/v1/feedback/', include('api_v1.feedback.urls')),
    #path('api/v1/scheduling/', include('api_v1.scheduling.urls')),
    path('api/v1/scraping/', include('api_v1.scraping.urls')),
    path('admin/', admin.site.urls),
    path('', include('saas.urls')),
    path('', include('dashboard.urls')),
    path('', include('global_dashboard.urls')),
    path('email/', include('email_sys.urls')),
    path('i18n/', include('django.conf.urls.i18n')),
    path('oauth/', include('social_django.urls', namespace='social')),
    path('', include('social_django.urls', namespace='social')),
]


server/accounts/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from .models import Profile
from .models import User


# user: signup.html
class UserForm(UserCreationForm):
    #username   = forms.CharField(max_length=20, widget=forms.TextInput(attrs={'class': 'form-control'}))
    email      = forms.EmailField(label="Email", max_length=256, widget=forms.TextInput(attrs={'class': 'form-control', 'id': 'id_email', 'placeholder': "pigdata@example.com", 'pattern': '[a-z0-9._%+-]+@[a-z0-9.-]+\.[a-z]{2,3}$'}))
    password1  = forms.CharField(label="Password", widget=forms.PasswordInput(attrs={'class': 'form-control', 'id': 'id_password1', 'placeholder': 'Password'}))
    password2  = forms.CharField(label="Password Confirm", widget=forms.PasswordInput(attrs={'class': 'form-control', 'id': 'id_password2', 'placeholder': 'Retype password'}))

    class Meta:
        model = User
        fields = (
            'email',
            'password1',
            'password2',
        )

    def save(self, commit=True):
        user = super(UserForm, self).save(commit=False)
        user.email = self.cleaned_data['email']
        user.username = user.email

        if commit:
            user.save()
        return user


# user_profile: signup.html
class ProfileForm(forms.ModelForm):
    YES_NO_CHOICE     = ((1, 'はい'), (0, 'いいえ'))

    first_name = forms.CharField(label="First Name", max_length=15, widget=forms.TextInput(attrs={'class': 'form-control', 'id': 'id_first_name', 'style ': "margin-left: -50px;", 'placeholder': 'First Name'}))
    last_name  = forms.CharField(label="Last Name", max_length=15, widget=forms.TextInput(attrs={'class': 'form-control', 'id': 'id_last_name', 'style':'margin-left: -50px;', 'placeholder': 'Last Name'}))

    first_name_kana   = forms.CharField(label="First Name (kana)", max_length=15, widget=forms.TextInput(attrs={'class': 'form-control', 'id': 'id_first_name_kana', 'style ': "margin-left: -50px;"}), required=False)
    last_name_kana    = forms.CharField(label="Last Name (kana)", max_length=15, widget=forms.TextInput(attrs={'class': 'form-control', 'id': 'id_last_name_kana', 'style ': "margin-left: -50px;"}), required=False)

    company_name      = forms.CharField(label="Company", max_length=30, widget=forms.TextInput(attrs={'class': 'form-control', 'id': 'id_company_name', 'placeholder': "会社名"}), required=False)
    company_name_kana = forms.CharField(label="Company (kana)", max_length=30, widget=forms.TextInput(attrs={'class': 'form-control', 'id': 'id_company_name_kana', 'placeholder': "会社名(カナ)"}), required=False)
    department        = forms.CharField(label="Department", max_length=30, widget=forms.TextInput(attrs={'class': 'form-control', 'id': 'id_department', 'placeholder': "部署名"}), required=False)
    job_title         = forms.CharField(label="Job Title", max_length=30, widget=forms.TextInput(attrs={'class': 'form-control', 'id': 'id_job_title', 'placeholder': "役職名"}), required=False)
    tel_number        = forms.CharField(label="Phone Number", max_length=18, widget=forms.TextInput(attrs={'class': 'form-control', 'id': 'id_tel_number', 'placeholder': "0300000000", 'pattern': '\d{2,4}\d{3,4}\d{3,4}'}), required=False)
    post_code         = forms.CharField(label="", max_length=15, widget=forms.TextInput(attrs={'class': 'form-control', 'id': 'id_post_code', 'placeholder': "1234567", 'pattern': '\d{3}\d{4}'}), required=False)
    address           = forms.CharField(label="", max_length=50, widget=forms.TextInput(attrs={'class': 'form-control', 'id': 'id_address', 'placeholder': "東京都中央区湊3-5-10"}), required=False)

    is_agree_user_pol     = forms.ChoiceField(widget=forms.RadioSelect(attrs={'class': 'choice'}), choices=YES_NO_CHOICE, initial=0, required=False)
    is_agree_privacy_pol  = forms.ChoiceField(widget=forms.RadioSelect(attrs={'class': 'choice'}), choices=YES_NO_CHOICE, initial=0, required=False)
    is_agree_security_pol = forms.ChoiceField(widget=forms.RadioSelect(attrs={'class': 'choice'}), choices=YES_NO_CHOICE, initial=0, required=False)

    class Meta:
        model = Profile
        fields = ('first_name', 'last_name', 'last_name_kana', 'first_name_kana', 'company_name', 'company_name_kana', 'department', 'job_title', 'tel_number', 'post_code', 'address', 'is_agree_user_pol', 'is_agree_privacy_pol', 'is_agree_security_pol')

#profile_change.html - Not used
class UserChangeForm(forms.ModelForm):
    username   = forms.CharField(max_length=20, widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder': "pigdata@example.com", 'disabled':True}), required=False)
    first_name = forms.CharField(max_length=15, widget=forms.TextInput(attrs={'class': 'form-control', 'id': 'id_first_name'}))
    last_name  = forms.CharField(max_length=15, widget=forms.TextInput(attrs={'class': 'form-control', 'id': 'id_last_name'}))

    class Meta:
        model = User
        #fields = ['username', 'first_name', 'last_name']
        fields = ['first_name', 'last_name']


# user_profile: profile_change.html
class ProfileChangeForm(forms.ModelForm):
    first_name        = forms.CharField(max_length=15, widget=forms.TextInput(attrs={'class': 'form-control', 'id': 'id_first_name'}))
    last_name         = forms.CharField(max_length=15, widget=forms.TextInput(attrs={'class': 'form-control', 'id': 'id_last_name'}))
    first_name_kana   = forms.CharField(max_length=15, widget=forms.TextInput(attrs={'class': 'form-control', 'id': 'id_first_name_kana'}))
    last_name_kana    = forms.CharField(max_length=15, widget=forms.TextInput(attrs={'class': 'form-control', 'id': 'id_last_name_kana'}))
    company_name      = forms.CharField(max_length=30, widget=forms.TextInput(attrs={'class': 'form-control', 'id': 'id_company_name', 'placeholder': "会社名"}))
    company_name_kana = forms.CharField(max_length=30, widget=forms.TextInput(attrs={'class': 'form-control', 'id': 'id_company_name_kana', 'placeholder': "会社名(カナ)"}))
    department        = forms.CharField(max_length=30, widget=forms.TextInput(attrs={'class': 'form-control', 'id': 'id_department', 'placeholder': "部署名"}), required=False)
    job_title         = forms.CharField(max_length=30, widget=forms.TextInput(attrs={'class': 'form-control', 'id': 'id_job_title', 'placeholder': "役職名"}), required=False)
    tel_number        = forms.CharField(max_length=18, widget=forms.TextInput(attrs={'class': 'form-control', 'id': 'id_tel_number', 'placeholder': "0300000000", 'pattern': '\d{2,4}\d{3,4}\d{3,4}'}), required=False)
    post_code         = forms.CharField(max_length=15, widget=forms.TextInput(attrs={'class': 'form-control', 'id': 'id_post_code', 'placeholder': "1234567", 'pattern': '\d{3}\d{4}'}), required=False)
    address           = forms.CharField(max_length=50, widget=forms.TextInput(attrs={'class': 'form-control', 'id': 'id_address', 'placeholder': "東京都中央区湊3-5-10"}), required=False)

    class Meta:
        model = Profile
        fields = ('first_name', 'last_name', 'first_name_kana', 'last_name_kana', 'company_name', 'company_name_kana', 'department', 'job_title', 'tel_number', 'post_code', 'address')

    def save(self, commit=True, update_fields=None):
        profile_change_form = super(ProfileChangeForm, self).save(commit=False)

        if commit:
            profile_change_form.save(update_fields=update_fields)
        return profile_change_form


server/accounts/templates/account_activation.html
{% extends "product_site_base.html" %}
{% load static %}
{% load i18n %}

{% block title %}本登録完了{% endblock %}

{% block css %}
{% endblock %}

{% block js %}
{% endblock %}

{% block content %}
<div class="main-panel" style="height: 95vh;">
    <div class="title">
        <h2>新規アカウント作成</h2>
    </div>
    <div class="background_wrapper">
        <div class="progress_icon">
            <p>
                <img src="{% static 'assets/images/progress-off01.png' %}" alt="基本情報入力">
                <img src="{% static 'assets/images/progress-arrow.png' %}" alt="arrow">
                <img src="{% static 'assets/images/progress-off02.png' %}" alt="仮登録完了">
                <img src="{% static 'assets/images/progress-arrow.png' %}" alt="arrow">
                <img src="{% static 'assets/images/progress-on-03.png' %}" alt="本登録完了">
            </p>
        </div>
        <div class="content">
            <hr />
            <div class="align_center">
                <h3 style="margin: 50px 0;">本登録が完了しました。</h3>
                <a href="{% url 'dashboard:product_download' %}"><button type="button" class="btn confirm">ダウンロード</button></a>
            </div>
        </div>
    </div>
</div>
{% endblock %}

server/accounts/templates/contact.html
{% extends "product_site_base.html" %}
{% load static %}
{% load i18n %}
{% block content%}
<div class="navbar">
	<a href="{% url 'accounts:home' %}" >Home</a>
	<a href="{% url 'accounts:product' %}" >{% trans "Products" %}</a>
	<a href="{% url 'accounts:learn' %}">{% trans "Learn" %}</a>
	<a href="{% url 'accounts:pricing' %}">{% trans "Pricing" %}</a>
	<a href="{% url 'accounts:about' %}">{% trans "About Us" %}</a>
	<a href="{% url 'accounts:contact' %}" class="active">{% trans "Contacts" %}</a>
	<a href="{% url 'accounts:login' %}" >{% trans "Login" %}</a>

	<!--div class="dropdown">
		<button class="dropbtn">en
			<i class="fa fa-caret-down"></i>
		</button>
		<div class="dropdown-content">
			<form>
			<a href="#" >ja</a>
			</form>
		</div>
	</div-->
</div>
<h2 class="major">{% trans "Contact" %}</h2>
			<form method="post" action="#">
				<div class="field half first">
					<label for="name">{% trans "Name" %}</label>
					<input type="text" name="name" id="name" />
				</div>
				<div class="field half">
					<label for="email">{% trans "Email" %}</label>
					<input type="text" name="email" id="email" />
				</div>
				<div class="field">
					<label for="message">{% trans "Message" %}</label>
					<textarea name="message" id="message" rows="4"></textarea>
				</div>
				<ul class="actions">
					<input type="submit" value="Send Message" class="special" />
					<input type="reset" value="Reset" />
				</ul>
			</form>

{% endblock%}

server/accounts/templates/global-login.html
{% extends "global-base.html" %}
{% load static %}
{% load i18n %}

{% block meta%}
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <meta name="description" content="">
  <meta name="author" content="">
{% endblock%}

{% block title%}
  Login
{% endblock%}

{% block css%}
  <!-- Custom fonts for this template-->
  <link href="vendor/fontawesome-free/css/all.min.css" rel="stylesheet" type="text/css">
  <link href="https://fonts.googleapis.com/css?family=Nunito:200,200i,300,300i,400,400i,600,600i,700,700i,800,800i,900,900i" rel="stylesheet">

  <!-- Custom styles for this template-->
  <link href="css/sb-admin-2.min.css" rel="stylesheet">
{% endblock%}

{% block content%}
    <!-- Outer Row -->
<section class="login" id="login">
    <div class="container">
    <div class="row justify-content-center">

      <div class="col-xl-10 col-lg-12 col-md-9">

        <div class="card o-hidden border-0 shadow-lg my-5">
          <div class="card-body p-0">
            <!-- Nested Row within Card Body -->
            <div class="row">
              <div class="col-lg-6 d-none d-lg-block bg-login-image"></div>
              <div class="col-lg-6">
                <div class="p-5">
                  <div class="text-center">
                    <h1 class="h4 text-gray-900 mb-4">Welcome</h1>
                  </div>
                  <form class="form-signin" method="post" action="{% url 'accounts:login' %}">
                    {% csrf_token %}
                    <div class="form-group">
                       <input type="text" class="form-control inputUsername" name="username" maxlength="254" required id="id_username" placeholder="Enter Email Address..." autofocus>
                    </div>
                    <div class="form-group">
                      <input type="password" class="form-control inputPassword" name="password" required id="id_password" placeholder="Password">
                    </div>
                    <div class="form-group">
                      <div class="custom-control custom-checkbox small">
                        <input type="checkbox" class="custom-control-input" id="customCheck">
                        <label class="custom-control-label" for="customCheck">Remember Me</label>
                      </div>
                    </div>
                    <!--<a href="index.html" class="btn btn-primary btn-user btn-block">-->
                      <!--Login-->
                    <!--</a>-->
                    <button class="btn btn-lg btn-primary btn-block btn-signin" type="submit">Login</button>
                    <hr>
                    <a href="{% url 'social:begin' 'google-oauth2' %}" class="btn btn-google btn-user btn-block">
                      <i class="fab fa-google fa-fw"></i> Login with Google
                    </a>
                    <a href="{% url 'social:begin' 'facebook' %}" class="btn btn-facebook btn-user btn-block">
                      <i class="fab fa-facebook-f fa-fw"></i> Login with Facebook
                    </a>
                  </form>
                  <hr>
                  <div class="text-center">
                    <a class="small" href="forgot-password.html">Forgot Password?</a>
                  </div>
                  <div class="text-center">
                    <a class="small" href="{% url 'accounts:global_signup' %}">Create an Account!</a>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>

      </div>

    </div>
    </div>
</section>
{% endblock%}

server/accounts/templates/global-sign-up.html
{% extends "global-base.html" %}
{% load static %}
{% load i18n %}

{% block meta%}
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <meta name="description" content="">
  <meta name="author" content="">
{% endblock%}

{% block title%}
  Login
{% endblock%}

{% block css%}
  <!-- Custom fonts for this template-->
  <link href="vendor/fontawesome-free/css/all.min.css" rel="stylesheet" type="text/css">
  <link href="https://fonts.googleapis.com/css?family=Nunito:200,200i,300,300i,400,400i,600,600i,700,700i,800,800i,900,900i" rel="stylesheet">

  <!-- Custom styles for this template-->
  <link href="css/sb-admin-2.min.css" rel="stylesheet">
{% endblock%}

{% block content%}
    <!-- Outer Row -->
<section class="signup" id="signup">
    <div class="container">
        {% if social_login_error %}
          <div class="alert alert-danger" id="error_msg" role="alert">
            {{ social_login_error }}
          </div>
        {% endif %}

        {% if user_form.errors or profile_form.errors%}
        <div class="alert alert-danger" role="alert">
            {% for form in user_form %}
                {% if form.errors %}<b>{% trans form.label %}</b>{{ form.errors }}{% endif %}
            {% endfor %}
            {% for form in profile_form %}
                {% if form.errors %}<b>{% trans form.label %}</b>{{ form.errors }}{% endif %}
            {% endfor %}
        </div>
        {% endif %}
        {% csrf_token %}
        <!-- Nested Row within Card Body -->
        <div class="row">
          <div class="col-lg-5 d-none d-lg-block bg-register-image"></div>
          <div class="col-lg-7">
            <div class="p-5">
              <div class="text-center">
                <h1 class="h4 text-gray-900 mb-4">Create an Account!</h1>
              </div>
              <form class="" ass="user" method="post" action="{% url 'accounts:global_signup' %}">
                {% csrf_token %}
                <div class="form-group row">
                  <div class="col-sm-6 mb-3 mb-sm-0">
                    {{ profile_form.first_name }}
                    <!--<input type="text" class="form-control form-control-user" id="exampleFirstName" placeholder="First Name">-->
                  </div>
                  <div class="col-sm-6">
                    {{ profile_form.last_name }}
                    <!-- <input type="text" class="form-control form-control-user" id="exampleLastName" placeholder="Last Name">
                    -->
                  </div>
                </div>
                <div class="form-group">
                  {{ user_form.email }}
                  <!-- <input type="email" class="form-control form-control-user" id="exampleInputEmail" placeholder="Email Address">
                  -->
                </div>
                <div class="form-group row">
                  <div class="col-sm-6 mb-3 mb-sm-0">
                    {{ user_form.password1 }}
                    <!-- <input type="password" class="form-control form-control-user" id="exampleInputPassword" placeholder="Password">
                    -->
                  </div>
                  <div class="col-sm-6">
                    {{ user_form.password2 }}
                    <!-- <input type="password" class="form-control form-control-user" id="exampleRepeatPassword" placeholder="Repeat Password">
                    -->
                  </div>
                </div>
                <div class="confirm-section">
                    <button id="submit_button" class="btn btn btn-primary btn-user btn-block confirm">
                      Register Account
                    </button>
                </div>
                <!--<hr>-->
                <!--<a href="index.html" class="btn btn-google btn-user btn-block">-->
                  <!--<i class="fab fa-google fa-fw"></i> Register with Google-->
                <!--</a>-->
                <!--<a href="index.html" class="btn btn-facebook btn-user btn-block">-->
                  <!--<i class="fab fa-facebook-f fa-fw"></i> Register with Facebook-->
                <!--</a>-->
              </form>
              <!--<hr>-->
              <div class="text-center">
                <a class="small" href="forgot-password.html">Forgot Password?</a>
              </div>
              <div class="text-center">
                <a class="small" href="login.html">Already have an account? Login!</a>
              </div>
            </div>
          </div>
        </div>
    </div>
</section>
{% endblock%}